baseURL: "/"

languageCode: "zh-cn"
defaultContentLanguage: "zh-cn"

title: ""

theme: "gokarna"

# 是否生成robots.txt
enableRobotsTXT: false

menu:
  main:
    - identifier: "home"
      name: "主页"
      url: "/"
      weight: 1

    - identifier: "posts"
      name: "归档"
      url: "/posts/"
      weight: 2

    - identifier: "t"
      name: "标签"
      url: "/tags/"
      weight: 3

    - identifier: "rss"
      url: "/index.xml"
      pre: "<span data-feather='rss'></span>"
      weight: 4

params:
    # 头像的URL
    avatarURL: "/images/avatar.png"
    # 头像尺寸size-xs、size-s、size-m、size-l、size-xl
    avatarSize: "size-l"
    # 标题和头像下的说明
    description: "Hello, world!"
    # a标签下的强调色
    accentColor: "#08F"

    customHeadHTML: "<script>
      const title = '小熊的博客';
      const emojis = ['🐻', '🐻‍❄️', '🐼', '🦝', '🧸'];
      let visible = false;
      let emojisIndex = 0;
      let currentTile = title + emojis[emojisIndex];

      document.title = currentTile;
      document.addEventListener('visibilitychange', ()=>{
        document.visibilityState === 'visible' ? 
        document.title = currentTile
        :
        document.title = '快看我 快看我'
       });
      document.addEventListener('visibilitychange', ()=>{
        document.visibilityState === 'visible' ? 
        visible = true
        :
        visible = false
       });

      setInterval(()=>{
        if(emojisIndex >= emojis.length - 1){
          emojisIndex = 0;
      }
      emojisIndex++;
      currentTile = title + emojis[emojisIndex];
      if(visible)
        document.title = currentTile;
      }, 1000);
      </script>"

    customFooterHTML: "<script>
      (document.getElementsByClassName('nav-title')[0]).getElementsByClassName('nav-brand')[0].innerText = title;
    </script>"

    # 在页脚部分显示的文本
    footer: "Text in footer"
    socialIcons:
      - name: "twitter"
        url: "https://twitter.com/SmallbearQwQ"
      - name: "telegram"
        url: "https://t.me/smallbrar"
      - name: "github"
        url: "https://github.com/xsmallbear"
      - name: "steam"
        url: "https://steamcommunity.com/profiles/76561198401072504"

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false